{"uuid":"f8d3d2ab-7a40-42b0-965d-3e94cc515142","historyId":"c59643030e1e776644fd5d1d6aa79cfc","status":"failed","statusDetails":{"message":"The following error originated from your test code, not from Cypress.\n\n  > requere is not defined\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","trace":"ReferenceError: The following error originated from your test code, not from Cypress.\n\n  > requere is not defined\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.\n    at ./cypress/e2e/Ui/Cadastrar.spec.js (https://conexaoqa.herokuapp.com/__cypress/tests?p=cypress\\e2e\\Ui\\Cadastrar.spec.js:100:15)\n    at __webpack_require__ (https://conexaoqa.herokuapp.com/__cypress/tests?p=cypress\\e2e\\Ui\\Cadastrar.spec.js:20:30)\n    at 0 (https://conexaoqa.herokuapp.com/__cypress/tests?p=cypress\\e2e\\Ui\\Cadastrar.spec.js:125:18)\n    at __webpack_require__ (https://conexaoqa.herokuapp.com/__cypress/tests?p=cypress\\e2e\\Ui\\Cadastrar.spec.js:20:30)\n    at eval (https://conexaoqa.herokuapp.com/__cypress/tests?p=cypress\\e2e\\Ui\\Cadastrar.spec.js:84:18)\n    at eval (https://conexaoqa.herokuapp.com/__cypress/tests?p=cypress\\e2e\\Ui\\Cadastrar.spec.js:87:10)\n    at eval (<anonymous>)\nFrom previous event:\n    at runScriptsFromUrls (https://conexaoqa.herokuapp.com/__cypress/runner/cypress_runner.js:179922:136)\n    at Object.runScripts (https://conexaoqa.herokuapp.com/__cypress/runner/cypress_runner.js:179937:12)\n    at $Cypress.onSpecWindow (https://conexaoqa.herokuapp.com/__cypress/runner/cypress_runner.js:168145:76)"},"stage":"finished","steps":[],"attachments":[],"parameters":[],"labels":[],"links":[],"start":1660662585912,"name":"An uncaught error was detected outside of a test","fullName":"An uncaught error was detected outside of a test","stop":1660662585961}